spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        - id: audit-service
          uri: lb://audit-service
          predicates:
            - Path=/api/v1/audit/**
          filters:
            - StripPrefix=2

        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/v1/task/**, /api/v1/project/**
          filters:
            - StripPrefix=2

        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

#        - id: discovery-server-static
#          uri: http://localhost:8761
#          predicates:
#            - Path=/eureka/**

server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE
