server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@discovery-server:8761/eureka
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        - id: audit-service
          uri: lb://audit-service
          predicates:
            - Path=/api/v1/audit/**
          filters:
            - StripPrefix=2

        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/v1/task/**, /api/v1/project/**
          filters:
            - StripPrefix=2

        - id: discovery-server
          uri: http://discovery-server:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: discovery-server-static
          uri: http://discovery-server:8761
          predicates:
            - Path=/eureka/**