spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5433/postgres
        username: postgres
        password: 1234qwer
    jpa:
        properties:
            hibernate:
                default_schema: app
                show_sql: true
                hbm2ddl.auto: validate
    mail:
        default-encoding: UTF-8
        host: smtp.gmail.com
        port: 587
        username: taskmanagerproject0@gmail.com
        password: gbivjewmzghjqxij

        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        test-connection: false
        protocol: smtp
    thymeleaf:
        check-template-location: false

    cloud:
        openfeign:
            client:
                config:
                    auditClient:
                        url: http://localhost:81/app/audit

server:
    port: 80
    error:
        include-message: always
app:
    email_service_prop:
        email_subject: Task Manager Verification
        redirect_url: http://localhost/users/verification
    jwt_prop:
        secret: NsasdOASDKFSDF123ASDKLAJFLSDKFJHEWUFHSDFNBHBwaEBjhbwe
        issuer: Alex
