server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@discovery-server:8761/eureka
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

spring:
  cloud:
    gateway:
      routes:

        - id: discovery-server
          uri: http://discovery-server:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: discovery-server-static
          uri: http://discovery-server:8761
          predicates:
            - Path=/eureka/**