spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://db:5431/task
        username: admin
        password: admin
    kafka:
        bootstrap-servers: http://broker:29092
eureka:
    client:
        service-url:
            defaultZone: http://admin:admin@discovery-server:8761/eureka

management:
    zipkin:
        tracing:
            endpoint: http://zipkin:9411/api/v2/spans
