spring:
    application:
        name: task-service
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5433/task
        username: postgres
        password: 1234qwer
    jpa:
        properties:
            hibernate:
                default_schema: app
                show_sql: true
                hbm2ddl.auto: validate
server:
    port: 0
    error:
        include-message: always

app:
    jwt_prop:
        secret: NsasdOASDKFSDF123ASDKLAJFLSDKFJHEWUFHSDFNBHBwaEBjhbwe
        issuer: Alex
eureka:
    client:
        service-url:
            defaultZone: http://admin:admin@localhost:8761/eureka
    instance:
        instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int}