spring:
    application:
      name: audit-service
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5433/audit
        username: postgres
        password: 1234qwer
    jpa:
        properties:
            hibernate:
                default_schema: app
                show_sql: true
                hbm2ddl.auto: validate
    kafka:
        bootstrap-servers: localhost:9092
        template:
            default-topic: auditTopic
        consumer:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            group-id: auditId
        properties:
            spring.json.type.mapping: event:by.itacademy.taskmanager.audit_service.core.dto.local.AuditCreateDTO
server:
    port: 0
    error:
        include-message: always

app:
    jwt_prop:
        secret: NsasdOASDKFSDF123ASDKLAJFLSDKFJHEWUFHSDFNBHBwaEBjhbwe
        issuer: Alex

eureka:
    client:
        service-url:
            defaultZone: http://admin:admin@localhost:8761/eureka
    instance:
        instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int}

management:
    tracing:
        sampling:
            probability: 1.0
