spring:
    config:
      import: optional:secret.yml
    application:
        name: user-service
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5433/user
        username: postgres
        password: 1234qwer
    jpa:
        properties:
            hibernate:
                default_schema: app
                show_sql: true
                hbm2ddl.auto: validate
    mail:
        default-encoding: UTF-8
        host: smtp.gmail.com
        port: 587
        username: username
        password: password

        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        test-connection: false
        protocol: smtp
    thymeleaf:
        check-template-location: false
    kafka:
      bootstrap-servers: localhost:9092
      template:
        default-topic: auditTopic
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
            spring.json.type.mapping: event:by.itacademy.taskmanager.userservice.core.dto.audit.AuditDTO

server:
    port: 0
    error:
        include-message: always
app:
    email_service_prop:
        email_subject: Task Manager Verification
        redirect_url: http://localhost/api/v1/users/verification
    jwt_prop:
        secret: NsasdOASDKFSDF123ASDKLAJFLSDKFJHEWUFHSDFNBHBwaEBjhbwe
        issuer: Alex
eureka:
    client:
        service-url:
            defaultZone: http://admin:admin@localhost:8761/eureka

management:
    tracing:
        sampling:
            probability: 1.0
