spring:
    application:
        name: user-service
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5433/user
        username: postgres
        password: 1234qwer
    jpa:
        properties:
            hibernate:
                default_schema: app
                show_sql: true
                hbm2ddl.auto: validate
    mail:
        default-encoding: UTF-8
        host: smtp.gmail.com
        port: 587
        username: taskmanagerproject0@gmail.com
        password: gbivjewmzghjqxij

        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        test-connection: false
        protocol: smtp
    thymeleaf:
        check-template-location: false

server:
    port: 0
    error:
        include-message: always
app:
    email_service_prop:
        email_subject: Task Manager Verification
        redirect_url: http://localhost/api/v1/users/verification
    jwt_prop:
        secret: NsasdOASDKFSDF123ASDKLAJFLSDKFJHEWUFHSDFNBHBwaEBjhbwe
        issuer: Alex
eureka:
    client:
        service-url:
            defaultZone: http://admin:admin@localhost:8761/eureka
